services:
  api1:
    image: api
    hostname: api1
    depends_on:
      - adatbazis
    expose:
      - "8888"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

  api2:
    image: api
    hostname: api2
    depends_on:
      - adatbazis
    expose:
      - "8888"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

  adatbazis:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '5GB'